=== fgaudenzi/testManager/testManager/XMLRepository/Certificate/certificate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.cumulus.org/certificate/cert"
    xmlns:cert="http://www.cumulus.org/certificate/cert">




    <xs:element name="Certificate" type="cert:CertificateType"/>
    <xs:complexType name="CertificateType">
        <xs:sequence>
            <xs:element name="CertificateId" type="xs:string"/>
            <xs:element name="CertificationModelId" type="xs:string"/>
            <xs:element name="CertifiedSecurityProperty" type="xs:string"/>
            <xs:element name="CertificateInfo" type="cert:certificateInfoType"> </xs:element>
            <xs:element name="CertificationDate" type="xs:date"/>
            <xs:element name="CertificateStatus" type="xs:string"/>
            <xs:element name="ExpirationDate" type="xs:dateTime"/>
            <xs:element name="Artifacts" type="cert:Artifacts"/>
            <xs:element name="Signature" type="cert:signatureType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="certificateInfoType">
        <xs:sequence maxOccurs="1" minOccurs="1">
            <xs:element name="CertificateType">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Test-based"/>
                        <xs:enumeration value="Monitor-based"/>
                        <xs:enumeration value="TPM-based"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="signatureType">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Role" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Artifacts">
        <xs:sequence>
            <xs:element name="Test-Artifact" minOccurs="0"/>
            <xs:element name="Monitor-Artifact" minOccurs="0"/>
            <xs:element name="TPM-Artificat" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== fgaudenzi/testManager/testManager/testManager/XMLRepository/Certificate/cert1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Certificate xmlns="http://www.cumulus.org/certificate/cert"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.cumulus.org/certificate/cert file:/Users/iridium/Documents/workspace/testManager/XMLRepository/Certificate/certificate.xsd">
    <CertificateId>1414059366167</CertificateId>
    <CertificationModelId>cumulus:cm:id:test:111</CertificationModelId>
    <CertifiedSecurityProperty>CSA:IAM:Account-control:Limitation-of-failed-user-authentication:triggerCount</CertifiedSecurityProperty>
    <CertificateInfo>
        <CertificateType>Test-based</CertificateType>
    </CertificateInfo>
    <CertificationDate>2014-10-23+02:00</CertificationDate>
    <CertificateStatus>not_issued</CertificateStatus>
    <ExpirationDate>2015-10-23T14:34:52.771+02:00</ExpirationDate>
    <Artifacts/>
    <Signature>
        <Name>CumulusCA</Name>
        <Role>TESTER</Role>
    </Signature>
</Certificate>
